name: Deploy to Debian VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Code herunterladen
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # 2. Deployment auf deine Debian VM
    - name: Deploy to VM (172.20.20.137)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Ins Projektverzeichnis wechseln
          cd ~/Projekte/Website/Website
          
          # Neuesten Code von GitHub holen
          git pull origin main
          
          # Alte Container stoppen
          sudo docker compose down
          
          # Neue Container bauen und starten
          sudo docker compose up -d --build
          
          # Status anzeigen
          sudo docker compose ps
          
          echo "✅ Deployment erfolgreich auf VM 172.20.20.137!"
